#!/bin/bash
#PBS -l select=1:ncpus=16:mem=124gb
#PBS -l walltime=12:00:00
#PBS -M andrew.j.jolly@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5345592/output_report
#PBS -J 1-500

cd /home/z5345592/scripts
source ~/.venvs/venv-tutorial-1/bin/activate

OUTPUT_FILE=/dev/null
if [[ ${PBS_ARRAY_INDEX} == 3 ]]; then
    OUTPUT_FILE="/srv/scratch/${USER}/${PBS_JOBNAME}.o${PBS_JOBID%%[^0-9]*}"
fi

python3 get_eso_stripped.py ${PBS_ARRAY_INDEX} &> ${OUTPUT_FILE}